### ISSUE TITLE
Expanding the evalutation example to include the recall argument

### ISSUE THREAD

**Issue by sephib** [vespa-engine/pyvespa#321]
Hi,
In the [Evaluation application](https://pyvespa.readthedocs.io/en/latest/evaluation.html#Evaluate-specific-query) documentation example, there is no mentioning of the option of using [**recall** for specific documetns](https://pyvespa.readthedocs.io/en/latest/query.html?highlight=recall#Recall-specific-documents).
Since this option can be very useful in an evaluation process - I'm suggesting to add   an example with the **recall** argument

```
top_ids = [...]

 query_evaluation = app.evaluate_query(
        eval_metrics = eval_metrics,
        query_model = query_model,
        query_id = query_data["query_id"],
        query = query_data["query"],
        id_field = "id",
        relevant_docs = query_data["relevant_docs"],
        default_score = 0,
        recall = ("id", top_ids[1:3]))
    )
```

**Comment by thigm85** [comment]
Hi @sephib, I am not sure if using `recall` in this use-case makes sense. When you call `evaluate_query` you want to evaluate the results returned by a specific `query_model` for a given `query`. 

Using `recall` here will contaminate the evaluation results by potentially including documents that wouldn't otherwise be returned by the query model. Am I missing something?

**Comment by thigm85** [comment]
Yes, it makes sense when you want to rank only specific document ids. I will add an example as suggested.
